####Data Wrangling
*It convert and format raw data to usable format down to data science pipeline


In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset_1=pd.read_csv('/content/dataset_1 - dataset_1 (1).csv')#load first dataset

In [ ]:
dataset_1   #first five rows

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [ ]:
dataset_1['instant'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
dataset_1['dteday'].unique()

array(['01-01-2011', '02-01-2011', '03-01-2011', '04-01-2011',
       '05-01-2011', '06-01-2011', '07-01-2011', '08-01-2011',
       '09-01-2011', '10-01-2011', '11-01-2011', '12-01-2011',
       '13-01-2011', '14-01-2011', '15-01-2011', '16-01-2011',
       '17-01-2011', '18-01-2011', '19-01-2011', '20-01-2011',
       '21-01-2011', '22-01-2011', '23-01-2011', '24-01-2011',
       '25-01-2011', '26-01-2011', '27-01-2011', '28-01-2011'],
      dtype=object)

In [ ]:
dataset_1['hr'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
dataset_1['weathersit'].unique()

array([1, 2, 3, 4])

In [ ]:
dataset_1['temp'].unique()

array([0.24, 0.22, 0.2 , 0.32, 0.38, 0.36, 0.42, 0.46, 0.44, 0.4 , 0.34,
       0.3 , 0.26, 0.16, 0.14, 0.18, 0.12, 0.28, 0.1 , 0.08, 0.06, 0.04,
       0.02])

In [ ]:
dataset_1.shape

(610, 10)

In [ ]:
dataset_1.shape[0]#only no of rows

610

In [ ]:
dataset_1.shape[1]#only no of columns

10

In [ ]:
dataset_2=pd.read_excel('/content/drive/My Drive/dataset_2.xlsx')#load second dataset

In [ ]:
dataset_2.head()

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81        0.0       3          13   16
1           1        2  0.2727  0.80        0.0       8          32   40
2           2        3  0.2727  0.80        0.0       5          27   32
3           3        4  0.2879  0.75        0.0       3          10   13
4           4        5  0.2879  0.75        0.0       0           1    1

In [ ]:
dataset_2.drop(['Unnamed: 0'],axis=1)

instant   atemp   hum  windspeed  casual  registered  cnt
0          1  0.2879  0.81     0.0000       3          13   16
1          2  0.2727  0.80     0.0000       8          32   40
2          3  0.2727  0.80     0.0000       5          27   32
3          4  0.2879  0.75     0.0000       3          10   13
4          5  0.2879  0.75     0.0000       0           1    1
..       ...     ...   ...        ...     ...         ...  ...
605      606  0.2121  0.93     0.1045       0          30   30
606      607  0.2121  0.93     0.1045       1          28   29
607      608  0.2121  0.93     0.1045       0          31   31
608      609  0.2727  0.80     0.0000       2          36   38
609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 7 columns]

In [ ]:
dataset_2.drop(['atemp'],axis=1)

Unnamed: 0  instant   hum  windspeed  casual  registered  cnt
0             0        1  0.81     0.0000       3          13   16
1             1        2  0.80     0.0000       8          32   40
2             2        3  0.80     0.0000       5          27   32
3             3        4  0.75     0.0000       3          10   13
4             4        5  0.75     0.0000       0           1    1
..          ...      ...   ...        ...     ...         ...  ...
605         605      606  0.93     0.1045       0          30   30
606         606      607  0.93     0.1045       1          28   29
607         607      608  0.93     0.1045       0          31   31
608         608      609  0.80     0.0000       2          36   38
609         609      610  0.86     0.0000       1          40   41

[610 rows x 7 columns]

In [ ]:
dataset_2.drop(['hum'],axis=1)

Unnamed: 0  instant   atemp  windspeed  casual  registered  cnt
0             0        1  0.2879     0.0000       3          13   16
1             1        2  0.2727     0.0000       8          32   40
2             2        3  0.2727     0.0000       5          27   32
3             3        4  0.2879     0.0000       3          10   13
4             4        5  0.2879     0.0000       0           1    1
..          ...      ...     ...        ...     ...         ...  ...
605         605      606  0.2121     0.1045       0          30   30
606         606      607  0.2121     0.1045       1          28   29
607         607      608  0.2121     0.1045       0          31   31
608         608      609  0.2727     0.0000       2          36   38
609         609      610  0.2576     0.0000       1          40   41

[610 rows x 7 columns]

In [ ]:
dataset_2.drop(['windspeed'],axis=1)

Unnamed: 0  instant   atemp   hum  casual  registered  cnt
0             0        1  0.2879  0.81       3          13   16
1             1        2  0.2727  0.80       8          32   40
2             2        3  0.2727  0.80       5          27   32
3             3        4  0.2879  0.75       3          10   13
4             4        5  0.2879  0.75       0           1    1
..          ...      ...     ...   ...     ...         ...  ...
605         605      606  0.2121  0.93       0          30   30
606         606      607  0.2121  0.93       1          28   29
607         607      608  0.2121  0.93       0          31   31
608         608      609  0.2727  0.80       2          36   38
609         609      610  0.2576  0.86       1          40   41

[610 rows x 7 columns]

In [ ]:
dataset_2.drop(['casual'],axis=1)

Unnamed: 0  instant   atemp   hum  windspeed  registered  cnt
0             0        1  0.2879  0.81     0.0000          13   16
1             1        2  0.2727  0.80     0.0000          32   40
2             2        3  0.2727  0.80     0.0000          27   32
3             3        4  0.2879  0.75     0.0000          10   13
4             4        5  0.2879  0.75     0.0000           1    1
..          ...      ...     ...   ...        ...         ...  ...
605         605      606  0.2121  0.93     0.1045          30   30
606         606      607  0.2121  0.93     0.1045          28   29
607         607      608  0.2121  0.93     0.1045          31   31
608         608      609  0.2727  0.80     0.0000          36   38
609         609      610  0.2576  0.86     0.0000          40   41

[610 rows x 7 columns]

In [ ]:
dataset_2.drop(['registered'],axis=1)

Unnamed: 0  instant   atemp   hum  windspeed  casual  cnt
0             0        1  0.2879  0.81     0.0000       3   16
1             1        2  0.2727  0.80     0.0000       8   40
2             2        3  0.2727  0.80     0.0000       5   32
3             3        4  0.2879  0.75     0.0000       3   13
4             4        5  0.2879  0.75     0.0000       0    1
..          ...      ...     ...   ...        ...     ...  ...
605         605      606  0.2121  0.93     0.1045       0   30
606         606      607  0.2121  0.93     0.1045       1   29
607         607      608  0.2121  0.93     0.1045       0   31
608         608      609  0.2727  0.80     0.0000       2   38
609         609      610  0.2576  0.86     0.0000       1   41

[610 rows x 7 columns]

In [ ]:
dataset_2.drop(['cnt'],axis=1)

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered
0             0        1  0.2879  0.81     0.0000       3          13
1             1        2  0.2727  0.80     0.0000       8          32
2             2        3  0.2727  0.80     0.0000       5          27
3             3        4  0.2879  0.75     0.0000       3          10
4             4        5  0.2879  0.75     0.0000       0           1
..          ...      ...     ...   ...        ...     ...         ...
605         605      606  0.2121  0.93     0.1045       0          30
606         606      607  0.2121  0.93     0.1045       1          28
607         607      608  0.2121  0.93     0.1045       0          31
608         608      609  0.2727  0.80     0.0000       2          36
609         609      610  0.2576  0.86     0.0000       1          40

[610 rows x 7 columns]

In [ ]:
dataset_1['weekday'].unique()

array([6, 0, 1, 2, 3, 4, 5])

In [ ]:
dataset_2['Unnamed: 0'].unique()


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
dataset_2['atemp'].median()


0.197

In [ ]:
bike_count=pd.merge(dataset_1,dataset_2,on='instant',how='inner')

In [ ]:
bike_count

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  Unnamed: 0   atemp   hum  windspeed  casual  registered  cnt  
0    0.24           0  0.2879  0.81     0.0000       3          13   16  
1    0.22           1  0.2727  0.80     0.0000       8          32   40  
2    0.22           2  0.2727  0.80     0.0000       5          27   32  
3    0.24           3  0.2879  0.75     0.0000       3          10   13  
4    0.24           4  0.2879  0.75     0.0000       0           1    1  
..    ...         ...     ...   ...        ...     ...         ...  ...  
605  0.18         605  0.2121  0.93     0.1045       0          30   30  
606  0.18         606  0.2121  0.93     0.1045       1          28   29  
607  0.18         607  0.2121  0.93     0.1045       0          31   31  
608  0.22         608  0.2727  0.80     0.0000       2          36   38  
609  0.20         609  0.2576  0.86     0.0000       1          40   41  

[610 rows x 17 columns]

In [ ]:
auto_price=pd.read_csv('/content/dataset_1 - dataset_1 (1).csv')
auto_price.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        1  01-01-2011       1   0     1   0    False        6           1   
1        2  01-01-2011       1   0     1   1    False        6           1   
2        3  01-01-2011       1   0     1   2    False        6           1   
3        4  01-01-2011       1   0     1   3    False        6           1   
4        5  01-01-2011       1   0     1   4    False        6           1   

   temp  
0  0.24  
1  0.22  
2  0.22  
3  0.24  
4  0.24

In [ ]:
auto_price.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday          bool
weekday         int64
weathersit      int64
temp          float64
dtype: object

In [ ]:
cols=['temp']
auto_price[cols]=auto_price[cols].apply(pd.to_numeric,args=('coerce',))

In [ ]:
auto_price[cols]

temp
0    0.24
1    0.22
2    0.22
3    0.24
4    0.24
..    ...
605  0.18
606  0.18
607  0.18
608  0.22
609  0.20

[610 rows x 1 columns]

In [ ]:
auto_price.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday          bool
weekday         int64
weathersit      int64
temp          float64
dtype: object

In [ ]:
auto_price.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [ ]:
auto_price.replace('?',np.nan,inplace=True)

In [ ]:
auto_price

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [ ]:
auto_price.isnull().sum()/auto_price.shape[0]*100   #percentage of missing value

instant       0.0
dteday        0.0
season        0.0
yr            0.0
mnth          0.0
hr            0.0
holiday       0.0
weekday       0.0
weathersit    0.0
temp          0.0
dtype: float64

In [ ]:
auto_price['weekday'].mode()# Mode is most frequent value

0    6
Name: weekday, dtype: int64

In [ ]:
auto_price['weathersit'].mode()

0    1
Name: weathersit, dtype: int64

In [ ]:
auto_price['temp'].median()

0.2

In [ ]:
auto_price['yr'].mean()

0.0